import type { PlaceableCategory, PlaceableKind, PlaceableSpec } from './types';

const SPECS: PlaceableSpec[] = [
  {
    kind: 'burger-kiosk',
    name: 'Copper Bun Kitchen',
    shortName: 'Burgers',
    category: 'food',
    icon: 'burger',
    description: 'Hot food with a two-person service counter. Guests leave with wrappers.',
    cost: 720,
    upkeep: 7,
    footprint: [5, 4],
    serviceNeed: 'hunger',
    capacity: 2,
    serviceSeconds: 5.8,
    revenue: 34,
    appeal: 8,
  },
  {
    kind: 'lemonade-stand',
    name: 'Citrus Press',
    shortName: 'Drinks',
    category: 'food',
    icon: 'cup',
    description: 'A compact cold-drink counter with quick service and recyclable cups.',
    cost: 460,
    upkeep: 4,
    footprint: [3, 3],
    serviceNeed: 'hunger',
    capacity: 1,
    serviceSeconds: 3.4,
    revenue: 19,
    appeal: 5,
  },
  {
    kind: 'ice-cream-cart',
    name: 'Moon Scoop Creamery',
    shortName: 'Ice Cream',
    category: 'food',
    icon: 'ice-cream',
    description: 'A chilled service cart for quick treats. Guests leave with compostable cups.',
    cost: 620,
    upkeep: 6,
    footprint: [3, 3],
    serviceNeed: 'hunger',
    capacity: 1,
    serviceSeconds: 4.2,
    revenue: 25,
    appeal: 7,
  },
  {
    kind: 'carousel',
    name: 'Constellation Carousel',
    shortName: 'Carousel',
    category: 'rides',
    icon: 'carousel',
    description: 'A luminous family ride with twelve places and strong park appeal.',
    cost: 1850,
    upkeep: 18,
    footprint: [9, 9],
    serviceNeed: 'fun',
    capacity: 6,
    serviceSeconds: 12,
    revenue: 24,
    appeal: 24,
  },
  {
    kind: 'sky-wheel',
    name: 'Aurora Sky Wheel',
    shortName: 'Sky Wheel',
    category: 'rides',
    icon: 'wheel',
    description: 'A landmark observation wheel with braced steelwork and eight gondolas.',
    cost: 3200,
    upkeep: 32,
    footprint: [12, 7],
    serviceNeed: 'fun',
    capacity: 8,
    serviceSeconds: 18,
    revenue: 32,
    appeal: 42,
  },
  {
    kind: 'bumper-cars',
    name: 'Voltage Bumper Hall',
    shortName: 'Bumper Cars',
    category: 'rides',
    icon: 'bumper-car',
    description: 'An eight-car electric pavilion with a conductive ceiling grid and impact rails.',
    cost: 2450,
    upkeep: 25,
    footprint: [11, 9],
    serviceNeed: 'fun',
    capacity: 8,
    serviceSeconds: 14,
    revenue: 27,
    appeal: 32,
  },
  {
    kind: 'drop-tower',
    name: 'Pulse Drop Tower',
    shortName: 'Drop Tower',
    category: 'rides',
    icon: 'drop-tower',
    description: 'A 13-metre lattice tower with a guided carriage, redundant brakes, and beacon crown.',
    cost: 3950,
    upkeep: 44,
    footprint: [8, 8],
    serviceNeed: 'fun',
    capacity: 8,
    serviceSeconds: 20,
    revenue: 35,
    appeal: 52,
  },
  {
    kind: 'pirate-ship',
    name: 'Copper Corsair',
    shortName: 'Pirate Ship',
    category: 'rides',
    icon: 'pirate-ship',
    description: 'A swinging ten-seat vessel on braced A-frames with a flywheel drive and air brakes.',
    cost: 3350,
    upkeep: 36,
    footprint: [12, 8],
    serviceNeed: 'fun',
    capacity: 10,
    serviceSeconds: 18,
    revenue: 31,
    appeal: 45,
  },
  {
    kind: 'restroom',
    name: 'Park Comfort Station',
    shortName: 'Restroom',
    category: 'facilities',
    icon: 'restroom',
    description: 'A ventilated, accessible comfort station that protects guest happiness.',
    cost: 880,
    upkeep: 11,
    footprint: [6, 4],
    serviceNeed: 'bladder',
    capacity: 4,
    serviceSeconds: 5.2,
    revenue: 0,
    appeal: 3,
  },
  {
    kind: 'first-aid',
    name: 'Pulse Point First Aid',
    shortName: 'First Aid',
    category: 'facilities',
    icon: 'first-aid',
    description: 'A staffed accessible clinic where tired guests can recover before returning to the park.',
    cost: 940,
    upkeep: 12,
    footprint: [5, 4],
    serviceNeed: 'rest',
    capacity: 2,
    serviceSeconds: 6.5,
    revenue: 0,
    appeal: 5,
  },
  {
    kind: 'information-booth',
    name: 'Park Pathfinder',
    shortName: 'Information',
    category: 'facilities',
    icon: 'information',
    description: 'Maps, accessibility guidance, and attraction tips from a compact two-window booth.',
    cost: 520,
    upkeep: 5,
    footprint: [4, 3],
    serviceNeed: 'information',
    capacity: 2,
    serviceSeconds: 3.2,
    revenue: 0,
    appeal: 8,
  },
  {
    kind: 'trash-bin',
    name: 'Sorting Bin',
    shortName: 'Bin',
    category: 'facilities',
    icon: 'bin',
    description: 'Captures nearby guest trash. Place one beside every food or ride exit.',
    cost: 85,
    upkeep: 1,
    footprint: [1, 1],
    serviceNeed: 'trash',
    capacity: 20,
    serviceSeconds: 0.8,
    revenue: 0,
    appeal: 1,
  },
  {
    kind: 'bench',
    name: 'Slatted Park Bench',
    shortName: 'Bench',
    category: 'decor',
    icon: 'bench',
    description: 'A timber-and-steel rest point that helps tired guests stay longer.',
    cost: 120,
    upkeep: 1,
    footprint: [2, 1],
    serviceNeed: 'rest',
    capacity: 2,
    serviceSeconds: 5,
    revenue: 0,
    appeal: 2,
  },
  {
    kind: 'park-lamp',
    name: 'Shielded Park Lamp',
    shortName: 'Lamp',
    category: 'decor',
    icon: 'lamp',
    description: 'Warm, downward-facing light with a bolted architectural base.',
    cost: 145,
    upkeep: 2,
    footprint: [1, 1],
    serviceNeed: null,
    capacity: 0,
    serviceSeconds: 0,
    revenue: 0,
    appeal: 3,
  },
  {
    kind: 'shade-tree',
    name: 'Copper Beech',
    shortName: 'Tree',
    category: 'decor',
    icon: 'tree',
    description: 'A mature shade tree with a guarded trunk and layered crown.',
    cost: 190,
    upkeep: 1,
    footprint: [3, 3],
    serviceNeed: null,
    capacity: 0,
    serviceSeconds: 0,
    revenue: 0,
    appeal: 5,
  },
];

export const PLACEABLE_SPECS: readonly PlaceableSpec[] = SPECS;

export const SPEC_BY_KIND = new Map<PlaceableKind, PlaceableSpec>(
  SPECS.map((spec) => [spec.kind, spec]),
);

export const CATEGORY_LABELS: Record<PlaceableCategory, string> = {
  food: 'Food',
  rides: 'Rides',
  facilities: 'Facilities',
  decor: 'Park details',
};

export function getPlaceableSpec(kind: PlaceableKind): PlaceableSpec {
  const spec = SPEC_BY_KIND.get(kind);
  if (!spec) {
    throw new Error(`Unknown placeable kind: ${kind}`);
  }
  return spec;
}
