import type { PlaceableCategory, PlaceableKind, PlaceableSpec } from './types';

const SPECS: PlaceableSpec[] = [
  {
    kind: 'burger-kiosk',
    name: 'Copper Bun Kitchen',
    shortName: 'Burgers',
    category: 'food',
    icon: 'burger',
    description: 'Hot food with a two-person service counter. Guests leave with wrappers.',
    cost: 720,
    upkeep: 7,
    footprint: [5, 4],
    serviceNeed: 'hunger',
    capacity: 2,
    serviceSeconds: 5.8,
    revenue: 34,
    appeal: 8,
  },
  {
    kind: 'lemonade-stand',
    name: 'Citrus Press',
    shortName: 'Drinks',
    category: 'food',
    icon: 'cup',
    description: 'A compact cold-drink counter with quick service and recyclable cups.',
    cost: 460,
    upkeep: 4,
    footprint: [3, 3],
    serviceNeed: 'hunger',
    capacity: 1,
    serviceSeconds: 3.4,
    revenue: 19,
    appeal: 5,
  },
  {
    kind: 'carousel',
    name: 'Constellation Carousel',
    shortName: 'Carousel',
    category: 'rides',
    icon: 'carousel',
    description: 'A luminous family ride with twelve places and strong park appeal.',
    cost: 1850,
    upkeep: 18,
    footprint: [9, 9],
    serviceNeed: 'fun',
    capacity: 6,
    serviceSeconds: 12,
    revenue: 46,
    appeal: 24,
  },
  {
    kind: 'sky-wheel',
    name: 'Aurora Sky Wheel',
    shortName: 'Sky Wheel',
    category: 'rides',
    icon: 'wheel',
    description: 'A landmark observation wheel with braced steelwork and eight gondolas.',
    cost: 3200,
    upkeep: 32,
    footprint: [12, 7],
    serviceNeed: 'fun',
    capacity: 8,
    serviceSeconds: 18,
    revenue: 72,
    appeal: 42,
  },
  {
    kind: 'restroom',
    name: 'Park Comfort Station',
    shortName: 'Restroom',
    category: 'facilities',
    icon: 'restroom',
    description: 'A ventilated, accessible comfort station that protects guest happiness.',
    cost: 880,
    upkeep: 11,
    footprint: [6, 4],
    serviceNeed: 'bladder',
    capacity: 4,
    serviceSeconds: 5.2,
    revenue: 0,
    appeal: 3,
  },
  {
    kind: 'trash-bin',
    name: 'Sorting Bin',
    shortName: 'Bin',
    category: 'facilities',
    icon: 'bin',
    description: 'Captures nearby guest trash. Place one beside every food or ride exit.',
    cost: 85,
    upkeep: 1,
    footprint: [1, 1],
    serviceNeed: 'trash',
    capacity: 20,
    serviceSeconds: 0.8,
    revenue: 0,
    appeal: 1,
  },
  {
    kind: 'bench',
    name: 'Slatted Park Bench',
    shortName: 'Bench',
    category: 'decor',
    icon: 'bench',
    description: 'A timber-and-steel rest point that helps tired guests stay longer.',
    cost: 120,
    upkeep: 1,
    footprint: [2, 1],
    serviceNeed: 'rest',
    capacity: 2,
    serviceSeconds: 5,
    revenue: 0,
    appeal: 2,
  },
  {
    kind: 'park-lamp',
    name: 'Shielded Park Lamp',
    shortName: 'Lamp',
    category: 'decor',
    icon: 'lamp',
    description: 'Warm, downward-facing light with a bolted architectural base.',
    cost: 145,
    upkeep: 2,
    footprint: [1, 1],
    serviceNeed: null,
    capacity: 0,
    serviceSeconds: 0,
    revenue: 0,
    appeal: 3,
  },
  {
    kind: 'shade-tree',
    name: 'Copper Beech',
    shortName: 'Tree',
    category: 'decor',
    icon: 'tree',
    description: 'A mature shade tree with a guarded trunk and layered crown.',
    cost: 190,
    upkeep: 1,
    footprint: [3, 3],
    serviceNeed: null,
    capacity: 0,
    serviceSeconds: 0,
    revenue: 0,
    appeal: 5,
  },
];

export const PLACEABLE_SPECS: readonly PlaceableSpec[] = SPECS;

export const SPEC_BY_KIND = new Map<PlaceableKind, PlaceableSpec>(
  SPECS.map((spec) => [spec.kind, spec]),
);

export const CATEGORY_LABELS: Record<PlaceableCategory, string> = {
  food: 'Food',
  rides: 'Rides',
  facilities: 'Facilities',
  decor: 'Park details',
};

export function getPlaceableSpec(kind: PlaceableKind): PlaceableSpec {
  const spec = SPEC_BY_KIND.get(kind);
  if (!spec) {
    throw new Error(`Unknown placeable kind: ${kind}`);
  }
  return spec;
}
